# ! MUST use CuDNN v8.0 => Python 3.6-3.8 , TensorFlow 2.4
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - azureml-defaults
      - azureml-mlflow
      - mlflow[tensorflow]
      - tensorflow==2.4.*
      - matplotlib
      - numpy
      - pandas
